### ISSUE TITLE
Can't compile only 1 Nuget Package registered

### ISSUE THREAD

**Issue by codingyourlife** [jorupp/ExportTestCases#9]
In the packages.config is only the HtmlAgilityPack registered and I can't find all the other missing references via Nuget. I couldn't even try the application once becaouse I couldn't find a compiled version of your tool on the internet.

Just try git clone command to a new folder and I think  you will see what I mean...

**Comment by jorupp** [comment]
I'll check on that, but I'm guessing it's the TFS SDK libs, though now that I think about it, I don't know that I ever checked for Nuget versions of those.

**Comment by codingyourlife** [comment]
Did you try this out too? I can compile now but I'm not able to connect to TFS. A dll doesn't fit I guess.

**Comment by jorupp** [comment]
It worked to connect to my TFS 2013 (on-prem) setup this morning when I tried.  Not sure if it'd be able to connect to an older (or newer) version, but I'd expect it to be able to give you something intelligible if it can't.

**Comment by codingyourlife** [comment]
Yeah found out what the problem was. This post helped: http://stackoverflow.com/a/34140080/828184 
I wanted to push it and see if the problem still exists with a new git clone request but I think you need to add me as contributor or something cause I get a 403 forbidden.

**Comment by jorupp** [comment]
Ok, you have collab rights - push up what you got working in a branch, and let's see if we can find a clever way to make it work without committing a bunch of binary blobs.

It's also possible that there's a better set of nuget packages to use than the ones supplied by the nuget-bot.

**Comment by codingyourlife** [comment]
Took me 2 pushes to really fix it. I had to add those 2 DLLs to a _Libs folder in the project. This Nuget package really isn't that good, but at least it works now. You are too fast with those binaries upload man, tried it and they gives me the exception I just fixed. Don't take this personal, nice to have someone responsive on this problem :)
